#!/usr/bin/env bash
# Teardown 02 setup: run vercel/ai-chatbot locally at $0, with ONE upstream file swapped.
#
#   RUN_DIR (default: this session's scratchpad on C:) gets a copy of teardowns/_src/ai-chatbot.
#   Why C:? node_modules is ~900 MB and G: had ~2 GB free on 2026-10-03.
#
# Steps: copy upstream -> pnpm install (+ @ai-sdk/google, pglite) -> swap lib/ai/providers.ts ->
# write .env.local (no Redis, no Blob, no Gateway) -> record the diff.
# Then, in three terminals from RUN_DIR:
#   node pg-server.mjs ./.pglite 5433                     # Postgres (PGlite) on 5433
#   npx tsx lib/db/migrate.ts                             # their migrations, unmodified
#   npx next dev --port 3091                              # (or preview_start "teardown-02-chatbot")
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$(cd "$HERE/../../.." && pwd)"
SRC="$WORKSPACE/teardowns/_src/ai-chatbot"
RUN_DIR="${RUN_DIR:?set RUN_DIR to where the runnable copy should live}"

if [ ! -d "$RUN_DIR/node_modules" ]; then
  mkdir -p "$RUN_DIR" && cp -r "$SRC/." "$RUN_DIR/" && rm -rf "$RUN_DIR/.git"
  (cd "$RUN_DIR" && npx -y pnpm@10.32.1 install --frozen-lockfile --ignore-scripts \
    && npx -y pnpm@10.32.1 add @ai-sdk/google @electric-sql/pglite @electric-sql/pglite-socket --ignore-scripts)
fi

cp "$HERE/providers.ts" "$RUN_DIR/lib/ai/providers.ts"
cp "$HERE/pg-server.mjs" "$RUN_DIR/pg-server.mjs"
diff -u --strip-trailing-cr "$SRC/lib/ai/providers.ts" "$HERE/providers.ts" \
  | sed "s|$SRC/||; s|$HERE/||" > "$HERE/providers.patch" || true

# Secrets: read GEMINI_API_KEY from the workspace .env without echoing it.
GEMINI_API_KEY="$(grep -E '^GEMINI_API_KEY=' "$WORKSPACE/.env" | head -1 | cut -d= -f2-)"
AUTH_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")"
cat > "$RUN_DIR/.env.local" <<EOF
# teardown 02 - generated by harness/setup.sh. No REDIS_URL / BLOB / AI_GATEWAY on purpose.
AUTH_SECRET=$AUTH_SECRET
POSTGRES_URL=postgres://postgres@127.0.0.1:5433/postgres
GEMINI_API_KEY=$GEMINI_API_KEY
EOF
echo "ready: $RUN_DIR (providers.ts swapped, .env.local written)"
