"""Tools: a Python callable, a Pydantic argument model, and the JSON schema the model sees.

Lab 04 built this by hand and validated arguments by simply calling the function and
catching `TypeError`. That is the right way to learn it and the wrong way to ship it: a
`TypeError` tells you a keyword did not bind, not that `city` was 40,000 characters long
or that `limit` was -1. CLAUDE.md's "Pydantic models at every boundary" applies here more
than anywhere, because this boundary is the one place where text generated by a language
model - text that an attacker upstream may have influenced - becomes arguments to code
that actually runs.

The three-way split from lab 04 survives intact, and it is worth restating:

    the function        what runs. The model never sees it.
    the schema          what the model sees. Billed as input tokens on EVERY request of
                        the loop, so its wording is high-leverage prompt text, not a
                        docstring.
    the registry        what is allowed to run. A name not in here cannot execute, which
                        is what makes a hallucinated tool name a non-event.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from pydantic import BaseModel, ValidationError

from .schema import to_provider_schema


class ToolError(Exception):
    """The tool ran and said no, in words the *model* should read and act on.

    Distinct from an unexpected exception on purpose. A ToolError is a recoverable turn in
    the conversation ("that city is not in my data, here are the ones that are"). An
    unexpected exception is a bug in our code, and telling the model "your call failed"
    teaches it to retry something that can never work.
    """


@dataclass(frozen=True)
class Tool:
    """One tool: name, the prompt-shaped description, its argument model, and the callable.

    `func` receives a *validated* instance of `args_model` and returns a string. A string,
    not an object, because the tool result travels back in a message's `content` field -
    same as any user message. Returning minified JSON is the convention here: lab 02
    measured pretty-printing the same object at +52% tokens, and this string is re-sent as
    input on every remaining step of the loop.
    """

    name: str
    description: str
    args_model: type[BaseModel]
    func: Callable[[Any], str]

    def schema(self) -> dict[str, Any]:
        """The OpenAI tool schema, generated from the Pydantic model.

        Generated rather than hand-written so the schema and the validation can never
        drift apart - the classic bug where a parameter was renamed in the model and the
        model keeps being told the old name.
        """
        # Normalised in one shared place (schema.py) so a tool schema and a structured
        # output schema can never disagree about what a provider will accept.
        parameters = to_provider_schema(self.args_model)
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": parameters,
            },
        }


@dataclass(frozen=True)
class ToolOutcome:
    """The result of one requested call, in the two forms the loop needs.

    `content` goes back to the model verbatim. `detail` is the one-liner for a human
    reading logs. They differ because the audiences differ.
    """

    call_id: str
    name: str
    ok: bool
    content: str
    detail: str


def _error_payload(kind: str, message: str) -> str:
    return json.dumps({"error": kind, "message": message}, separators=(",", ":"))


def dispatch(registry: dict[str, Tool], call_id: str, name: str, raw_arguments: str) -> ToolOutcome:
    """Run one tool call. Never raises; every failure becomes a tool result.

    That is a protocol requirement, not politeness: the OpenAI message format demands
    exactly one message with `role: "tool"` for every id in the assistant's `tool_calls`.
    Skip one and the next request is a 400.

    Failure order, each a distinct real-world case:
      1. the name is not registered        -> hallucinated or stale tool
      2. `arguments` is not valid JSON     -> truncation, or the model freelancing
      3. the arguments fail validation     -> wrong types, missing fields, out of range
      4. the tool itself says no           -> ToolError
      5. the tool crashes                  -> our bug, reported as ours
    """
    tool = registry.get(name)
    if tool is None:
        known = ", ".join(sorted(registry)) or "(none registered)"
        return ToolOutcome(
            call_id,
            name,
            False,
            _error_payload(
                "unknown_tool",
                f"there is no tool named {name!r}. Available tools: {known}. Use one of "
                "those or answer without a tool.",
            ),
            f"unknown tool {name!r} - refused, not executed",
        )

    try:
        parsed = json.loads(raw_arguments or "{}")
    except json.JSONDecodeError as exc:
        return ToolOutcome(
            call_id,
            name,
            False,
            _error_payload(
                "invalid_json_arguments",
                f"your `arguments` field was not valid JSON ({exc.msg} at position "
                f"{exc.pos}). Re-issue the call with a complete, valid JSON object.",
            ),
            f"json.loads failed: {exc.msg} at pos {exc.pos}",
        )

    try:
        args = tool.args_model.model_validate(parsed)
    except ValidationError as exc:
        # Pydantic's own message names the field and the rule that failed, which is far
        # more actionable as a prompt than anything paraphrased. Truncated because it is
        # re-sent as input tokens on every subsequent step.
        return ToolOutcome(
            call_id,
            name,
            False,
            _error_payload("invalid_arguments", f"argument validation failed: {exc}"[:600]),
            f"ValidationError: {exc.error_count()} error(s)",
        )

    try:
        result = tool.func(args)
    except ToolError as exc:
        return ToolOutcome(
            call_id, name, False, _error_payload("tool_failed", str(exc)), f"ToolError: {exc}"
        )
    except Exception as exc:  # noqa: BLE001 - our bug, not the model's
        return ToolOutcome(
            call_id,
            name,
            False,
            _error_payload(
                "tool_crashed",
                f"{name} crashed internally ({type(exc).__name__}). This is a bug in the "
                "tool, not in your call. Do not retry it; report it and continue.",
            ),
            f"CRASH in {name}: {type(exc).__name__}: {str(exc)[:110]}",
        )

    if not isinstance(result, str):
        result = json.dumps(result, separators=(",", ":"), default=str)
    preview = result if len(result) <= 90 else result[:87] + "..."
    return ToolOutcome(call_id, name, True, result, f"ok -> {preview}")
